services:
  - type: web
    name: help-alphaclin
    env: python
    plan: free
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements.txt && python migrate_data.py
    startCommand: gunicorn --workers 1 --bind 0.0.0.0:$PORT run:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: helpalphaclin-db
          property: connectionString
      - key: LOG_LEVEL
        value: WARNING
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_EMAIL
        value: admin@helpalphaclin.com
      - key: ADMIN_PASSWORD
        generateValue: true

databases:
  - name: helpalphaclin-db
    databaseName: helpalphaclin
    user: helpalphaclin